# Generated by Django 5.1.3 on 2024-11-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousPlaceOfStudyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('patronymic', models.CharField(default='', max_length=150)),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
                ('individual_identical_number', models.CharField(default='', max_length=50)),
                ('on_the_budget', models.BooleanField(default=1)),
                ('language_of_study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.languageofstudy')),
                ('previous_place_of_study_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.previousplaceofstudytype')),
                ('quota', models.ManyToManyField(to='admissions.quota')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.specialty')),
            ],
        ),
    ]
