# Generated by Django 5.1.3 on 2024-12-03 03:08

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_languageofstudy_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='entrant',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='entrant',
            name='study_format',
            field=models.CharField(choices=[('Очное обучение', 'Очное обучение'), ('Заочное обучение', 'Заочное обучение')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='entrant',
            name='citizenship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.citizenshiplist'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.nationality'),
        ),
    ]
