# Generated by Django 5.1.4 on 2025-02-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_citizenshiplist_nationality_entrant_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='citizenshiplist',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='nationality',
            managers=[
            ],
        ),
    ]
